name: Build PartyPlugin

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore
        run: nuget restore PartyPlugin.sln

      - name: Build
        run: msbuild PartyPlugin.sln /p:Configuration=Release /p:Platform="Any CPU"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PartyPluginBuild
          path: |
            bin/Release/**/*
